### ISSUE TITLE
Not displaying correct quality color

### ISSUE THREAD

**Issue by Klixxx** [cr4ckp0t/ElvUI_ItemLevelDatatext#1]
Hello Lockslap,

Klix here, the itemlevel datatext you've updated dosent pull the correct quality color for the gear:

![image](https://user-images.githubusercontent.com/33373965/58466861-d4377000-813a-11e9-9a0e-4a0bc87262d3.png)

**Comment by cr4ckp0t** [comment]
Hey man, yeah I noticed that as well and believe I have fixed it.
