### ISSUE TITLE
does this still work?

### ISSUE THREAD

**Issue by grand-lotus-iroh** [cr4ckp0t/ElvUI_ItemLevelDatatext#2]
what is the AVAILABLE TAG that I use in the custom text area?

![image](https://user-images.githubusercontent.com/1291364/105248565-9de70980-5b44-11eb-8369-0869f68fbed9.png)

I notice the plugin is being loaded but I do not see the available tag.

**Comment by cr4ckp0t** [comment]
That is not added by this addon.
